name: my_money_v3
description: A money tracker application.

version: 1.0.3+16

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  mockito: ^5.4.0
  path_provider: ^2.1.5
  persian_datetime_picker: ^3.0.2
  pie_chart: ^5.4.0
  shared_preferences: ^2.0.15
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_test: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - lang/fa.json
    - lang/en.json
    - assets/images/logo.png

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/IRANSans_Black.ttf
          weight: 900
        - asset: assets/fonts/IRANSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANSans_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans.ttf
          weight: 400
        - asset: assets/fonts/IRANSans_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans_UltraLight.ttf
          weight: 200
