name: my_money_v3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  flex_color_scheme: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  persian_datetime_picker: ^2.5.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lang/fa.json
    - lang/en.json
    - assets/images/logo.png

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-FD-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazirmatn-FD-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-FD-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-FD-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-FD-Thin.ttf
          weight: 100