name: my_money_v3
description: A money tracker application.

version: 1.0.3+14

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^8.0.2
  shared_preferences: ^2.0.15
  flex_color_scheme: ^7.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  persian_datetime_picker: ^3.0.2
  uuid: ^4.5.1
  mockito: ^5.4.0
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_test: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - lang/fa.json
    - lang/en.json
    - assets/images/logo.png

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-FD-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazirmatn-FD-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-FD-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-FD-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-FD-Thin.ttf
          weight: 100
