// Mocks generated by Mockito 5.4.0 from annotations
// in my_money_v3/test/features/home/data/repositories/home_info_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_money_v3/features/home/data/datasources/home_info_local_data_source.dart'
    as _i3;
import 'package:my_money_v3/features/home/data/models/home_info_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeInfoModel_0 extends _i1.SmartFake implements _i2.HomeInfoModel {
  _FakeHomeInfoModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeInfoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeInfoLocalDataSource extends _i1.Mock
    implements _i3.HomeInfoLocalDataSource {
  MockHomeInfoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeInfoModel> getHomeInfo() => (super.noSuchMethod(
        Invocation.method(
          #getHomeInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.HomeInfoModel>.value(_FakeHomeInfoModel_0(
          this,
          Invocation.method(
            #getHomeInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HomeInfoModel>);
}
